//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumption
    {
        public int id { get; set; }
        public System.DateTime usedDate { get; set; }
        public Nullable<int> product_id { get; set; }
        public int usedQuantity { get; set; }
        public Nullable<int> treatment_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual treatment treatment { get; set; }
    }
}
