//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CrudLogInEntities : DbContext
    {
        public DB_CrudLogInEntities(string x)
            : base(x)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<tarea> tareas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<consumption> consumptions { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<specialist> specialists { get; set; }
        public virtual DbSet<speciality> specialities { get; set; }
        public virtual DbSet<treatment> treatments { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
