//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        public int task_id { get; set; }
        public string taskname { get; set; }
        public System.DateTime start_date { get; set; }
        public System.TimeSpan estimated_time { get; set; }
        public string employee { get; set; }
        public string project { get; set; }
    }
}
