//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public treatment()
        {
            this.consumptions = new HashSet<consumption>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public decimal standardCost { get; set; }
        public decimal standardConsumption { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> specialistId { get; set; }
        public Nullable<int> adminId { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumption> consumptions { get; set; }
        public virtual patient patient { get; set; }
        public virtual specialist specialist { get; set; }
        public virtual user user { get; set; }
    }
}
